### ISSUE TITLE
Random verse?

### ISSUE THREAD

**Issue by ZyriabDsgn** [anthony-halim/bible-verse.nvim#19]
Hello,
First of, thanks a lot for this great plugin, I was looking into making my own and found yours, that's nice :)

I was wondering if it was possible to query a random verse.
If not, do you accept PRs? I thought about adding an option to display a random verse on startup.

God bless

**Comment by anthony-halim** [comment]
Feel free to create a PR to add additional functionality, I would be happy to accept contributions :) thank you for checking out the plugin!

**Comment by josh-ramer** [comment]
Glad to see this in the works. I look forward to adding it to my dashboard!

**Comment by josh-ramer** [comment]
<img width="1414" alt="image" src="https://github.com/anthony-halim/bible-verse.nvim/assets/38678260/b5a43011-f3f7-4bc9-865f-c6e89c92db7d">

**Comment by josh-ramer** [comment]
<img width="815" alt="neovim-dashboard" src="https://github.com/anthony-halim/bible-verse.nvim/assets/38678260/db9e0632-77db-487d-bd11-67312be2a01e">

Waiting with anticipation!

**Comment by anthony-halim** [comment]
Hi, the feature has been merged in #21. 

Please see this [comment](https://github.com/anthony-halim/bible-verse.nvim/pull/20#issuecomment-1763234073).

Looking at your screenshot, it might also be beneficial if I can fetch daily verse somewhere and return it to user. I will look it into it :)

**Comment by anthony-halim** [comment]
https://github.com/anthony-halim/bible-verse.nvim#-recipes 

I have included a sample integration with dashboards in the README. Enjoy 👍
